import React from 'react'
import omnicorn1 from './images/omnicorn1.png'

const ViewGuidelines = () => {
  return (
    <>
    <div className='bg-danger-subtle opacity-50 mt-3 mr-3'><h2 className='text-center text-secondary '>COVID Omicron BF.7: Symptoms, Causes and Precaution</h2>
    <img
    src={omnicorn1}
    width="800"
    height="auto"
    className="float-right align-top text-center mt-1"
    alt=""
  />
  <h3 className='text-secondary ml-3'>Overview</h3>
  <p className='p-2 ml-5 text-secondary lh-base'>
Since the emergence of the COVID-19 variant Omicron in late 2021, it has evolved rapidly into multiple sub variants. One subvariant, Omicron BF.5.2.1.7 (also called Omicron BF.7), 
which is driving the current COVID infection wave in China, has left the World Health Organization (WHO) “very concerned” reviving fears across the world, including India. 

Apart from the UK, US and European countries like Denmark, France, Germany and Belgium, cases of BF.7 infection have been detected in India too. 

Questions are being raised on what this new variant is about, its symptoms, and whether it will cause a fresh wave in India.</p>
 
  <h3 className='text-secondary ml-3'>What are the symptoms of the BF.7 variant?</h3>
  <p className='p-2 ml-5 text-secondary lh-base'>
Symptoms of infection with BF.7 are similar to those of other omicron sub-variants, primarily upper respiratory infection, including running nose, cough, fever and sore throat.The infection may be more severe in those with weaker immune systems.

</p>
<h3 className='text-secondary ml-3'>What could be the cause of faster spread?</h3>
<p className='p-2 ml-5 text-secondary lh-base'>
As per studies, the R0 value of this mutant is about 10-18.6 which means that the infected people can infect 10-18.6 people around them.

BF.7 variant carries a particular mutation ‘R346T’ in the spike protein of the SARS-CoV-2 (a protein on the surface of coronavirus that allows it to attach to and infect the cells). 

This mutation, which is also seen in variant BA.5 (parent of BF.7), has been linked with increasing the capacity of the virus to escape neutralizing antibodies generated by previous infections or vaccines. This means the antibodies from vaccination are not effective enough against this virus.</p>
<h3 className='text-secondary ml-3'>Who is at higher risk of infection with the Omicron BF.7 variant?</h3>
<p className='p-2 ml-5 text-secondary lh-base'>
People who are not vaccinated are at a higher risk. Also, people with weaker immunity, like children, elderly citizens, pregnant women and those with multiple comorbidities, such as uncontrolled diabetes, cancer, kidney or heart diseases, are at a higher risk of catching this infection.
</p>
<h3 className='text-secondary ml-3'>What Precaution Can Be Taken to Prevent Infection with BF.7?</h3>
<p className='p-2 ml-5 text-secondary lh-base'>

With Christmas and New Year celebrations around the corner, it is very critical than ever to follow COVID-appropriate behaviour. Hand sanitization, wearing a mask and maintaining social distancing remains the basic steps to prevent a potential spread.

While cough, cold, and other seasonal diseases are common during these months in India, you should never ignore these symptoms. If you or someone around you have a cough, cold and other symptoms, get a COVID test done immediately and practice self-isolation.</p>
</div>

  </>

  )
}

export default ViewGuidelines